USERS_TABLE = """
CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
telegram_id INTEGER UNIQUE,
name TEXT,
username TEXT,
instagram TEXT,
region TEXT,
district TEXT,
fest_id TEXT,
referrer_id INTEGER,
referrals_count INTEGER DEFAULT 0,
points INTEGER DEFAULT 0,
is_registered INTEGER DEFAULT 0,
is_subscribed INTEGER DEFAULT 0,
is_blocked INTEGER DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""

WINNERS_TABLE = """
CREATE TABLE IF NOT EXISTS winners(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
winner_type TEXT,
prize TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""

BROADCAST_TABLE = """
CREATE TABLE IF NOT EXISTS broadcasts(
id INTEGER PRIMARY KEY AUTOINCREMENT,
text TEXT,
total INTEGER,
success INTEGER,
failed INTEGER,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""
